'use strict';

export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION'
export const GET_TRUCKS_BY_LOCATION = 'GET_TRUCKS_BY_LOCATION'
export const FILTER_BY_GEOLOCATION = 'FILTER_BY_GEOLOCATION'
export const TRANSMIT_BOX_DIMENSIONS = 'TRANSMIT_BOX_DIMENSIONS'
export const FILTER_BY_FOOD_TYPE = 'FILTER_BY_FOOD_TYPE'
export const REPOSITION_MAP = 'REPOSITION_MAP'
export const SHOW_TRUCK_DETAILS = 'SHOW_TRUCK_DETAILS'
